/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef data_CONSTANTS_H
#define data_CONSTANTS_H

#include "data_types.h"

namespace Thread_Lock_Mutex {

class dataConstants {
 public:
  dataConstants();

};

extern const dataConstants g_data_constants;

} // namespace

#endif
