/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "data_constants.h"

namespace Thread_Lock_Mutex {

const dataConstants g_data_constants;

dataConstants::dataConstants() {
}

} // namespace

